app:  #应用基本配置
  env: 'local'  #环境名称
  port: 8088  #服务监听端口
  app_name: 'naio'  #应用名称
  app_url: 'http://localhost'  #应用域名

log:
  level: 'info' # 日志等级
  root_dir: './storage/logs' # 日志根目录
  filename: 'app.log' # 日志文件名称
  format: '' # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

database:
  driver: 'mysql' # 数据库驱动
  host: '127.0.0.1' # 域名
  port: 3306 # 端口号
  database: 'naio' # 数据库名称
  username: 'root' # 用户名
  password: 'pzzrudlf' # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: 'info' # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: 'sql.log' # 日志文件名称

redis:
  host: '127.0.0.1'
  port: 6379
  db: 1
  password: ''

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 43200

storage:
  default: 'local'
  disks: 
    local:
      root_dir: './storage/app'
      app_url: 'http://localhost:8088/storage'
    ali_oss: 
      access_key_id: 'access_key_id'
      access_key_secret: 'access_key_secret'
      bucket: 'bucket'
      endpoint: 'endpoint'
      is_ssl: true
      is_private: false
    qi_niu:
      access_key: 'access_key'
      bucket: 'bucket'
      domain: 'domain'
      secret_key: 'secret_key'
      is_ssl: true
      is_private: false
